export const GETUSERS_LOADING = 'GETUSERS_LOADING';
export const GETUSERS_SUCCESS = 'GETUSERS_SUCCESS';
export const GETUSERS_ERROR = 'GETUSERS_ERROR';
export const GETUSERS_DEBOUNCING_LOADING = 'GETUSERS_DEBOUNCING_LOADING';
export const GETUSERS_DEBOUNCING_SUCCESS = 'GETUSERS_DEBOUNCING_SUCCESS';
export const GETUSERS_DEBOUNCING_ERROR = 'GETUSERS_DEBOUNCING_ERROR';

export interface GetUsersActionTypes {
    type: string;
    payload?: any;
}